# https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        exclude: ^private.key$
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: |
          (?x)^(
            .*/tsconfig.json
            |.*/.vscode/.*
          )$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets
  - repo: https://github.com/sbrunner/hooks
    rev: 1.1.2
    hooks:
      - id: copyright
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.142.7
    hooks:
      - id: renovate-config-validator
